<DashboardScreen>:
    name: "DashboardScreen"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(12)
        spacing: dp(8)

        # ================= Header =================

        MDCard:
            elevation: 1
            radius: [16]
            size_hint_y: None
            height: dp(50)

            MDBoxLayout:
                padding: dp(10), dp(0)
                spacing: dp(8)

                MDLabelA:
                    id: counter_label
                    text: f"Dashboard"
                    font_style: "Subtitle1"
                    bold: True
                    valign: "middle"
                    halign: "left"
                    text_size: self.size

                Widget:

                AsyncIconButton:
                    id: refresh_btn
                    icon: "refresh"

                    before: root.befor_load_dashboard
                    task: root.load_dashboard_data
                    after: root.after_load_dashboard
                    error_handler: root.handle_load_dashboard

        # ================= Scroll =================

        ScrollView:

            MDBoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(15)
                padding: dp(10)

                ##################################################
                # TODAY CARD
                ##################################################
                MDCard:
                    orientation: "vertical"
                    size_hint_y: None
                    height: dp(230)

                    radius: [16, 16, 16, 16]
                    elevation: 2
                    padding: dp(20)

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: dp(14)
                        padding: [dp(20), dp(20), dp(20), dp(20)]
                        spacing: dp(14)

                        MDLabel:
                            text: "Today's Progress"
                            font_style: "H6"
                            bold: True
                            size_hint_y: None
                            height: self.texture_size[1]
                        
                        MDSeparator:

                        MDBoxLayout:
                            orientation: "horizontal"
                            size_hint: None, None
                            spacing: dp(6)
                            pos_hint: {"center_x": .5}
                            width: self.minimum_width
                            height: self.minimum_height

                            MDLabel:
                                id: today_review_label
                                text: "2 Reviews"
                                font_style: "H4"
                                bold: True
                                adaptive_size: True
                            
                            MDLabel:
                                id: today_study_time_label
                                text: "(1.0m)"
                                font_style: "H5"
                                bold: True
                                adaptive_size: True
                                theme_text_color: "Custom"
                                text_color: 0.2, 0.6, 1, 1

                        MDProgressBar:
                            id: today_progress
                            value: 0
                            max: 100
                            size_hint_y: None
                            height: dp(8)

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)

                            MDLabel:
                                id: remaining_label
                                text: "0 cards remaining"
                                theme_text_color: "Secondary"

                            MDLabel:
                                id: completion_percent
                                text: "0%"
                                halign: "right"
                                bold: True

                ##################################################
                # SUMMARY
                ##################################################
                
                MDGridLayout:
                    cols: 2
                    spacing: dp(12)
                    row_default_height: dp(100)
                    row_force_default: True
                    size_hint_y: None
                    height: self.minimum_height
                
                    ##################################################
                    # STREAK
                    ##################################################
                
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)
                
                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)

                                MDIcon:
                                    icon: "fire"
                                    theme_text_color: "Custom"
                                    text_color: 1.00, 0.44, 0.26, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)
                                    pos_hint: {"center_y": 0.5}

                                MDLabel:
                                    text: "Current Streak"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: streak_label
                                text: "0 Days"
                                font_style: "H5"
                                halign: "center"
                                bold: True
                                size_hint_y: None
                                height: self.texture_size[1]
                
                    ##################################################
                    # DUE TODAY
                    ##################################################
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)                            
                
                                MDIcon:
                                    icon: "calendar-clock"
                                    theme_text_color: "Custom"
                                    text_color:0.94, 0.33, 0.31, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "Due Today"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: due_today_label
                                text: "0"
                                font_style: "H5"
                                bold: True
                                halign: "center"
                                size_hint_y: None
                                height: self.texture_size[1]
                
                    ##################################################
                    # TOTAL CARDS
                    ##################################################
                
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)                            
                
                                MDIcon:
                                    icon: "cards"
                                    theme_text_color: "Custom"
                                    text_color: 0.13, 0.59, 0.95, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "Total Cards"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: total_cards_label
                                text: "0"
                                font_style: "H5"
                                bold: True
                                halign: "center"
                                size_hint_y: None
                                height: self.texture_size[1]
                
                    ##################################################
                    # MATURE
                    ##################################################
                
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)
                
                                MDIcon:
                                    icon: "school"
                                    theme_text_color: "Custom"
                                    text_color:0.30, 0.69, 0.31, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "Mature Cards"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: mature_label
                                text: "0"
                                font_style: "H5"
                                bold: True
                                halign: "center"
                                size_hint_y: None
                                height: self.texture_size[1]

                    ##################################################
                    # study time
                    ##################################################
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)
                
                                MDIcon:
                                    icon: "book-open-page-variant"
                                    theme_text_color: "Custom"
                                    text_color:0.61, 0.15, 0.69, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "estimate study time"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: study_time_label
                                text: "0"
                                font_style: "H5"
                                bold: True
                                halign: "center"
                                size_hint_y: None
                                height: self.texture_size[1]

                    ##################################################
                    # Today's Performance
                    ##################################################
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2

                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            ##################################################
                            # Header
                            ##################################################
                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)

                                MDIcon:
                                    icon: "star-circle"
                                    theme_text_color: "Custom"
                                    text_color:1.00, 0.76, 0.03, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "Today's Performance"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]

                            ##################################################
                            # yesterday Performance
                            ##################################################
                            
                            AnchorLayout:
                                anchor_x: "center"
                                anchor_y: "center"

                                MDBoxLayout:
                                    adaptive_width: True
                                    size_hint_y: None
                                    height: dp(22)
                                    spacing: dp(4)

                                    # ستاره‌ها
                                    MDBoxLayout:
                                        adaptive_width: True
                                        spacing: dp(2)

                                        MDIcon:
                                            id: star1
                                            theme_text_color: "Custom"
                                            text_color:1.00, 0.84, 0.31, 1
                                            icon: "star-outline"
                                            size_hint: None, None
                                            size: dp(20), dp(20)

                                        MDIcon:
                                            id: star2
                                            theme_text_color: "Custom"
                                            text_color:1.00, 0.84, 0.31, 1
                                            icon: "star-outline"
                                            size_hint: None, None
                                            size: dp(20), dp(20)

                                        MDIcon:
                                            id: star3
                                            theme_text_color: "Custom"
                                            text_color:1.00, 0.84, 0.31, 1
                                            icon: "star-outline"
                                            size_hint: None, None
                                            size: dp(20), dp(20)

                                        MDIcon:
                                            id: star4
                                            theme_text_color: "Custom"
                                            text_color:1.00, 0.84, 0.31, 1
                                            icon: "star-outline"
                                            size_hint: None, None
                                            size: dp(20), dp(20)

                                        MDIcon:
                                            id: star5
                                            theme_text_color: "Custom"
                                            text_color:1.00, 0.84, 0.31, 1
                                            icon: "star-outline"
                                            size_hint: None, None
                                            size: dp(20), dp(20)

                                    MDLabel:
                                        id: yesterday_Performance_lable
                                        text: "0.0 (0%)"
                                        adaptive_width: True
                                        bold: True
                    ##################################################
                    # reviewed count Performance
                    ##################################################
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)
                
                                MDIcon:
                                    icon: "trending-up"
                                    theme_text_color: "Custom"
                                    text_color:0.00, 0.78, 0.33, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "reviewed count Performance"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: reviewed_count_performance
                                text: "0"
                                font_style: "H5"
                                bold: True
                                halign: "center"
                                size_hint_y: None
                                height: self.texture_size[1]

                    ##################################################
                    #study_time
                    ##################################################
                    MDCard:
                        size_hint_y: None
                        height: dp(100)
                        radius: [14,14,14,14]
                        elevation: 2
                
                        MDBoxLayout:
                            orientation: "vertical"
                            padding: dp(16)
                            spacing: dp(8)

                            MDBoxLayout:
                                orientation: "horizontal"
                                size_hint_y: None
                                height: dp(32)
                                spacing: dp(8)
                
                                MDIcon:
                                    icon: "clock-check-outline"
                                    theme_text_color: "Custom"
                                    text_color: 0.20, 0.60, 0.86, 1
                                    icon_size: "24sp"
                                    size_hint: None, None
                                    size: dp(24), dp(24)

                                MDLabel:
                                    text: "study time"
                                    bold: True
                                    size_hint_y: None
                                    height: self.texture_size[1]
                
                            MDLabel:
                                id: study_time
                                text: "0"
                                font_style: "H5"
                                bold: True
                                halign: "center"
                                size_hint_y: None
                                height: self.texture_size[1]

                ##################################################
                # LEARNING PROGRESS
                ##################################################
                MDCard:
                    size_hint_y: None
                    height: dp(315)
                    radius: [16,16,16,16]
                    elevation: 2

                    MDBoxLayout:
                        orientation: "vertical"
                        padding: dp(20)
                        spacing: dp(14)

                        MDLabel:
                            text: "Learning Progress"
                            font_style: "H6"
                            bold: True
                            size_hint_y: None
                            height: self.texture_size[1]
                        
                        MDSeparator:

                        ##################################################
                        # NEW
                        ##################################################

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)
                            spacing: dp(8)

                            MDIcon:
                                icon: "plus-box"
                                theme_text_color: "Custom"
                                text_color:0.26, 0.65, 0.96, 1
                                width: dp(24)
                                icon_size: "24sp"
                                size_hint: None, None
                                size: dp(24), dp(24)


                            MDLabel:
                                text: "New Cards"

                            MDLabel:
                                id: new_count
                                text: "0 (0%)"
                                halign: "right"

                        MDProgressBar:
                            id: new_progress
                            value: 0
                            max: 100
                            size_hint_y: None
                            height: dp(8)

                        ##################################################
                        # LEARNING
                        ##################################################

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)
                            spacing: dp(8)

                            MDIcon:
                                icon: "brain"
                                theme_text_color: "Custom"
                                text_color:0.49, 0.34, 0.76, 1
                                width: dp(24)
                                icon_size: "24sp"
                                size_hint: None, None
                                size: dp(24), dp(24)

                            MDLabel:
                                text: "Learning"

                            MDLabel:
                                id: learning_count
                                text: "0 (0%)"
                                halign: "right"

                        MDProgressBar:
                            id: learning_progress
                            value: 0
                            max: 100
                            size_hint_y: None
                            height: dp(8)

                        ##################################################
                        # REVIEW
                        ##################################################

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)
                            spacing: dp(8)

                            MDIcon:
                                icon: "refresh"
                                theme_text_color: "Custom"
                                text_color:0.98, 0.55, 0.00, 1
                                width: dp(24)
                                icon_size: "24sp"
                                size_hint: None, None
                                size: dp(24), dp(24)

                            MDLabel:
                                text: "Review"

                            MDLabel:
                                id: review_count
                                text: "0 (0%)"
                                halign: "right"

                        MDProgressBar:
                            id: review_progress
                            value: 0
                            max: 100
                            size_hint_y: None
                            height: dp(8)

                        ##################################################
                        # MATURE
                        ##################################################

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)
                            spacing: dp(8)

                            MDIcon:
                                icon: "school"
                                theme_text_color: "Custom"
                                text_color: 0.30, 0.69, 0.31, 1
                                width: dp(24)
                                icon_size: "24sp"
                                size_hint: None, None
                                size: dp(24), dp(24)

                            MDLabel:
                                text: "Mature"

                            MDLabel:
                                id: mature_count
                                text: "0 (0%)"
                                halign: "right"

                        MDProgressBar:
                            id: mature_progress
                            value: 0
                            max: 100
                            size_hint_y: None
                            height: dp(8)
                ##################################################
                # UPCOMING REVIEWS
                ##################################################
                MDCard:
                    size_hint_y: None
                    height: dp(225)
                    radius: [16,16,16,16]
                    elevation: 2

                    MDBoxLayout:
                        orientation: "vertical"
                        padding: dp(20)
                        spacing: dp(12)

                        MDLabel:
                            text: "Upcoming Reviews"
                            font_style: "H6"
                            bold: True
                            size_hint_y: None
                            height: self.texture_size[1]

                        MDSeparator:

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)

                            MDLabel:
                                text: "Tomorrow"

                            MDLabel:
                                id: tomorrow_label
                                text: "0"
                                halign: "right"

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)

                            MDLabel:
                                text: "Next 3 Days"

                            MDLabel:
                                id: next3_label
                                text: "0"
                                halign: "right"

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)

                            MDLabel:
                                text: "Next 7 Days"

                            MDLabel:
                                id: next7_label
                                text: "0"
                                halign: "right"

                        MDBoxLayout:
                            size_hint_y: None
                            height: dp(24)

                            MDLabel:
                                text: "Next 30 Days"

                            MDLabel:
                                id: next30_label
                                text: "0"
                                halign: "right"