<FlashCardListScreen>:
    name: "FlashCardListScreen"
    
    RecycleView:
        id: RV
        viewclass: 'MDCardA'
        scroll_type: ['bars', 'content']
        bar_width: dp(10)

        RecycleBoxLayout:
            orientation: 'vertical'
            spacing: dp(15)
            padding: dp(10)

            size_hint_y: None
            height: self.minimum_height

            default_size_hint: 1, None
            default_size: None, dp(375)
