<ReviewScreen>:
    name: "ReviewScreen"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(12)
        spacing: dp(8)

        ##################################################
        # Header
        ##################################################
        MDCard:
            elevation: 1
            radius: [16]
            size_hint_y: None
            height: dp(50)

            MDBoxLayout:
                padding: dp(10), dp(0)
                spacing: dp(8)

                MDLabelA:
                    id: counter_label
                    text: f"{root.arrow} Done: {root.total_today_reviews}  | Remaining: {root.remaining_cards}"
                    font_style: "Subtitle1"
                    bold: True
                    valign: "middle"
                    halign: "left"
                    size_hint_x: 1
                    shorten: True
                    shorten_from: "right"
                    max_lines: 1

                MDLabelA:
                    id: session_time_lable
                    text: root.session_time
                    font_style: "H6"
                    size_hint_x: 1
                    shorten: True
                    shorten_from: "left"        
                    halign: "right"          
                    valign: "middle"
                    max_lines: 1        

                MDIconButton:
                    id: toggle_session_btn
                    icon: "play"
                    disabled: False
                    theme_icon_color: "Custom"
                    icon_color: app.theme_cls.primary_color
                    on_release: root.toggle_session()

                AsyncIconButton:
                    id: refresh_btn
                    icon: "skip-next-outline"
                    before: root.before_refresh_session
                    task: root.refresh_session
                    after: root.after_refresh_session
                    error_handler: root.handle_refresh_session_error

                AsyncIconButton:
                    id: reload_card_btn
                    icon: "database-refresh"
                    before: root.before_reload_card
                    task: root.reload_current_card
                    after: root.after_reload_card
                    error_handler: root.handle_reload_card_error

        ##################################################
        # Complete Session
        ##################################################
        MDBoxLayout:
            id: compleat_Session_Box
            orientation: "vertical"
            spacing: dp(16)
            padding: dp(32)
            
            Widget:
            
            MDIconButton:
                id: session_status_icon
                icon: "pause-circle-outline"
                halign: "center"
                icon_size: "84sp"
                theme_icon_color: "Custom"
                icon_color: app.theme_cls.primary_color
                on_release: root.toggle_session()
                pos_hint: {"center_x": .5}

            MDLabelA:
                id: session_title
                font_style: "H5"
                bold: True
                halign: "center"

            MDLabelA:
                id: session_description
                font_style: "Body1"
                halign: "center"
                theme_text_color: "Secondary"

            Widget:
        
        ##################################################
        # Flash Card
        ##################################################
        ScrollView:
            id: flashcard_box
            size_hint_y: None
            height: 0
            opacity: 0
            disabled: True

            MDBoxLayout:
                orientation: "vertical"
                size_hint_y: None
                adaptive_height: True

                padding:  dp(10), dp(10), dp(10), dp(10)
                spacing: dp(8)
        
                MDCard:
                    orientation: "vertical"
                    size_hint_x: 1
                    size_hint_y: None
                    adaptive_height: True
                    padding: dp(20)
                    spacing: dp(8)
                    radius: [20]
                    elevation: 2

                    ##################################################
                    # Word
                    ##################################################

                    MDLabelA:
                        id: title_label
                        text: ""
                        font_style: "H4"
                        bold: True
                        adaptive_height: True

                    MDLabelA:
                        id: pronunciation_label
                        text: ""
                        font_style: "Subtitle1"
                        font_name : root.IPA_FONT
                        theme_text_color: "Secondary"
                        adaptive_height: True

                    ##################################################
                    # Chips
                    ##################################################

                    MDBoxLayout:
                        adaptive_height: True
                        spacing: dp(8)

                        MDChipA:
                            id: pos_chip
                            icon: "alphabetical-variant"

                        MDChipA:
                            id: type_chip
                            icon: "shape"

                        MDChipA:
                            id: level_chip
                            icon: "chart-bar"

                        MDChipA:
                            id: box_chip
                            icon: "package-variant"

                    MDSeparator:

                    ##################################################
                    # Verb Forms
                    ##################################################

                    MDBoxLayout:
                        id: verb_forms_box
                        adaptive_height: True
                        padding: 0, dp(5)
                        spacing: dp(8)

                        MDLabelA:
                            text: "Past:"
                            bold: True
                            size_hint_x: None
                            width: dp(55)

                        MDLabelA:
                            id: past_tense_label
                            theme_text_color: "Secondary"

                        MDLabelA:
                            text: "Past Participle:"
                            bold: True
                            size_hint_x: None
                            width: dp(125)

                        MDLabelA:
                            id: past_participle_label
                            theme_text_color: "Secondary"

                    MDSeparator:
                        height: dp(1)

                    ##################################################
                    # Collocation
                    ##################################################

                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: dp(6)

                        MDBoxLayout:
                            adaptive_height: True
                            spacing: dp(8)

                            MDIcon:
                                icon: "format-list-bulleted"
                                theme_text_color: "Primary"
                                size_hint_x: None
                                width: dp(10)

                            MDLabelA:
                                text: "Collocations"
                                bold: True
                                font_style: "Subtitle1"

                        MDLabelA:
                            id: collocation_label
                            text: ""
                            text_size: self.width, None
                            adaptive_height: True
                            halign: "left"

                    MDSeparator:

                    ##################################################
                    # Example
                    ##################################################

                    MDBoxLayout:
                        id: example_box
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: dp(6)

                        MDBoxLayout:
                            adaptive_height: True
                            spacing: dp(8)

                            MDIcon:
                                icon: "lightbulb-on-outline"
                                theme_text_color: "Primary"
                                size_hint_x: None
                                width: dp(10)

                            MDLabelA:
                                text: "Example"
                                bold: True
                                font_style: "Subtitle1"

                        MDLabelA:
                            id: example_label
                            text: ""
                            text_size: self.width, None
                            adaptive_height: True
                            halign: "left"

                    MDSeparator:

                    ##################################################
                    # Definition
                    ##################################################

                    MDBoxLayout:
                        id: definition_box
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: dp(6)

                        MDBoxLayout:
                            adaptive_height: True
                            spacing: dp(8)

                            MDIcon:
                                icon: "book-open-page-variant"
                                theme_text_color: "Primary"
                                size_hint_x: None
                                width: dp(10)

                            MDLabelA:
                                text: "Definition"
                                bold: True
                                font_style: "Subtitle1"

                        MDLabelA:
                            id: definition_label
                            text: ""
                            text_size: self.width, None
                            adaptive_height: True
                            halign: "left"

                    MDSeparator:

                    ##################################################
                    # Audio
                    ##################################################
                    MDBoxLayout:
                        adaptive_height: True
                        spacing: dp(8)

                        MDIcon:
                            icon: "book-open-page-variant"
                            theme_text_color: "Primary"
                            size_hint_x: None
                            width: dp(10)

                        MDLabelA:
                            text: "Audio"
                            bold: True
                            font_style: "Subtitle1"

                    Playlist:
                        id: songs_playlist
                        size_hint_y: None
                        height: dp(250)
                        padding: dp(8), 0
                        spacing: dp(8)
                        time_slider_enabled: True
                        volume_slider_enabled: True

        BoxLayout:
            id: button_area
            orientation: "vertical"
            size_hint_y: None
            height: 0
        
            MDBoxLayout:
                id: button_box
                orientation: "horizontal"
                size_hint_y: None
                height: dp(46)
                spacing: dp(10)
                
                AsyncButton:
                    id: skip_btn
                    text: "Skip"
                    icon: "skip-next"
                    size_hint_x: 0.28
                    md_bg_color: app.theme_cls.primary_light
                    before: root.before_skip_card
                    task: root.skip_card
                    after: root.after_skip_card
                    error_handler: root.handle_skip_card_error
        
                BaseButtonA:
                    id: show_answer_btn
                    text: "Show Answer"
                    icon: "eye"
                    size_hint_x: 0.72
                    md_bg_color: app.theme_cls.primary_color
                    on_release: root.show_answer_fields()
        
            MDBoxLayout:
                id: answer_button_box
                orientation: "horizontal"
                size_hint_y: None
                height: 0
                opacity: 0
                disabled: True
        
                spacing: dp(10)
        
                BaseButtonA:
                    id: hide_answer_btn
                    text: "Hide"
                    icon: "eye-off"
                    size_hint_x: 1
                    md_bg_color: app.theme_cls.primary_light
                    on_release: root.hide_answer_fields()
        
                AsyncButton:
                    id: again_btn
                    text: "Again"
                    icon: "reload-alert"
                    size_hint_x: 1
                    md_bg_color: "#D32F2F"
                    
                    before: root.before_mark_quality
                    task: root.quality_task(0)
                    after: root.quality_after(0)
                    error_handler: root.handle_mark_quality_error
        
                AsyncButton:
                    id: hard_btn
                    text: "Hard"
                    icon: "alert-circle"
                    size_hint_x: 1
                    md_bg_color: "#FB8C00"
                    
                    before: root.before_mark_quality
                    task: root.quality_task(1)
                    after: root.quality_after(1)
                    error_handler: root.handle_mark_quality_error
        
                AsyncButton:
                    id: good_btn
                    text: "Good"
                    icon: "thumb-up"
                    size_hint_x: 1
                    md_bg_color: "#1E88E5"
                    
                    before: root.before_mark_quality
                    task: root.quality_task(2)
                    after: root.quality_after(2)
                    error_handler: root.handle_mark_quality_error
        
                AsyncButton:
                    id: easy_btn
                    text: "Easy"
                    icon: "emoticon"
                    size_hint_x: 1
                    md_bg_color: "#43A047"
                    
                    before: root.before_mark_quality
                    task: root.quality_task(3)
                    after: root.quality_after(3)
                    error_handler: root.handle_mark_quality_error
        
                AsyncButton:
                    id: very_easy_btn
                    text: "Very Easy"
                    icon: "emoticon-happy"
                    size_hint_x: 1
                    md_bg_color: "#2E7D32"
                    before: root.before_mark_quality
                    task: root.quality_task(4)
                    after: root.quality_after(4)
                    error_handler: root.handle_mark_quality_error